### ISSUE TITLE
Changes to the rdflib-endpoint dependency

### ISSUE THREAD

**Issue by vemonet** [proycon/codemeta-server#1]
Hi @proycon, I made some changes to [rdflib-endpoint](https://github.com/vemonet/rdflib-endpoint) that will impact how the endpoint is deployed in your app

Starting from v0.3.0 you can define on which path the SPARQL endpoint will be deployed, and the YASGUI will not be deployed on / by default. YASGUI is now served on the same path as the SPARQL endpoint when the request headers ask for text/html in Accept (when people access it through the browser)

To fix this you might want to add a line with `path="/sparql",`  when instantiating the SparqlEndpoint class:
https://github.com/proycon/codemeta-server/blob/master/codemeta_server/main.py#L101

Let me know if you are facing any issue with this new approach!

**Comment by vemonet** [comment]
Actually I just released `0.4.0` which adds a new class `SparqlRouter` to create the SPARQL endpoint as an `APIRouter` instead of a full `FastAPI`. So you can directly mount the SPARQL endpoint to an existing API with `app.include_router()`

So you would just need to change your `SparqlEndpoint` to `SparqlRouter` and include it to your API with `app.include_router(sparql_router)`

**Comment by proycon** [comment]
Thanks a lot for the heads-up and your work on rdflib-endpoint! I will adapt my code accordingly!
